// playgrounds/next/app/page.tsx
// eslint-disable-next-line antfu/no-import-dist
import type { Post } from "../../../dist/index";
import { initLocalify } from "@/localify";

export default async function Home() {
  const localify = await initLocalify();
  const posts = localify.getPosts();
  return (
    <ul>
      {Object.keys(posts).map((key) => {
        const post = posts[key];
        return (
          <li key={key}>
            <h2>{post.title}</h2>
            <p>{post.date}</p>
            <p>{post.excerpt}</p>
          </li>
        );
      })}
    </ul>
  );
}

// playgrounds/nuxt/app/app.vue
<template>
  <div>
    <p>{{ message }}</p>
  </div>
</template>

<script setup lang="ts">
import type { Post } from "../../../dist/index.d.ts"  
import Localify from "../../../dist/index"

const message = ref<Record<string, Post> | null>(null);

const initLocalify = async () => {
  const localify = new Localify(process.cwd(), {
    localDb: true,
    draft: true,
    excerpt: ''
  })
  await localify.init();
  message.value = localify.getPosts();
}

initLocalify();
</script>
